stages:
  - build

build-catalog:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build services/catalog/Catalog.Api.csproj

build-orders:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build services/orders/Orders.Api.csproj

build-frontend:
  stage: build
  image: node:22-alpine
  script:
    - cd frontend && npm install && npm run build
